laboratory/views/laboratory.py

Issue 29 fixed

---

src/laboratory/static/laboratory/js/substance_creation.js
src/laboratory/sustance/forms.py
src/laboratory/sustance/views.py
src/laboratory/templates/laboratory/sustance/list.html
src/laboratory/templates/laboratory/sustance/substance_deleteview.html
src/laboratory/templates/laboratory/sustance/sustance_form.html
src/laboratory/urls.py
src/presentation/static/css/organilab.css

Added autocomplete feature to h code, laboratory, features and white organ fields in substance add view, refactor and bugfixing in substance/views.py

Reactives view stew

---

src/laboratory/templatetags/laboratory.py
src/presentation/templates/gentelella/app/sidebar.html

Add 'view_organizationstructure' permission in the file templatestag laboratory.

Set permissions

---

src/authentication/users.py
src/laboratory/templates/laboratory/access_management.html
src/laboratory/templates/laboratory/laboratory_list.html
src/laboratory/views/access.py
src/laboratory/views/laboratory.py
src/presentation/templates/gentelella/app/sidebar.html
src/presentation/templates/gentelella/app/top_navigation.html
src/presentation/templates/partials/laboratories_menu.html

This PR migrate tree permissions structure to django permissions, each view look for django permissions to do an specific action and check in some views related to laboratories if the user has it assigned and if it is so grant the permissions to do whatever actions he can do according to the django permissions.
Each laboratory has an access list of users that can permform actions in this entity:
Also we can add organizations:
And that's it...

Change permissions validation

---

src/authentication/forms.py
src/authentication/users.py
src/laboratory/forms.py
src/laboratory/gtselects.py
src/laboratory/static/laboratory/css/users.css
src/laboratory/templates/laboratory/users_management.html
src/laboratory/views/access.py

Roles to profile

---

src/authentication/users.py
src/laboratory/views/access.py

Now the profile permission can be removed automatically by removing the profile.

Can delete profile permission

---

src/academic/templates/academic/procedure_list.html
src/laboratory/forms.py
src/presentation/templates/gentelella/app/top_navigation.html

issue#176 
text fields required in create providers
position in top_navigation

Org tony176

---

src/academic/templates/academic/procedure_list.html
src/laboratory/forms.py
src/presentation/templates/gentelella/app/top_navigation.html

Org tony179

---

src/academic/forms.py

fix forms ModalObject

---

src/laboratory/templates/laboratory/laboratoryroom_form.html
src/risk_management/templates/risk_management/incidentreport_form.html
src/risk_management/templates/risk_management/incidentreport_list.html
src/risk_management/templates/risk_management/riskzone_confirm_delete.html
src/risk_management/templates/risk_management/riskzone_detail.html
src/risk_management/templates/risk_management/riskzone_form.html
src/risk_management/templates/risk_management/riskzone_list.html

Matching risk management template style with laboratory template style, some changes were:
- Buttons(size, position, group, color, background type(outline))
- Remove and add some divs(type row) to locate forms, containers and buttons in an appropriate way.

Update style risk management

---

src/laboratory/api/shelfobject.py

- Add extra validation for permissions the user should have to access the endpoints.
- Add a dictionary to keep track of the required permissions by endpoint.

Permission Validation Improvement

---

src/laboratory/api/shelfobject.py
src/laboratory/shelfobject/forms.py
src/laboratory/shelfobject/serializers.py
src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/templates/laboratory/serializers/shelfobject_actions.html
src/laboratory/templates/laboratory/shelfobject/action_modal.html
src/laboratory/views/labroom.py

This is just the format setup, transfer_out is WIP.

- Setting up the format for the API endpoint for transfer_out.

---

src/laboratory/api/shelfobject.py
src/laboratory/shelfobject/serializers.py
src/laboratory/static/laboratory/js/laboratory.js

- Finish up transfer_out endpoint, validations and frontend.
- Update the clear_action_form method to also reset the switchery inputs.

Transfer Out Functionality

---

src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/templates/laboratory/serializers/shelfobject_actions.html
src/laboratory/templates/laboratory/shelfobject/action_modal.html
src/presentation/templates/modal_template.html

- Update transfer out to use the new way to manage and show modals.
- Fix some issues found during the implementation of the changes.

Transfer Out Fixes and Improvements

---

src/laboratory/api/shelfobject.py
src/laboratory/shelfobject/serializers.py
src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/templates/laboratory/laboratoryroom_list.html
src/laboratory/templates/laboratory/serializers/shelfobject_actions.html
src/laboratory/templates/laboratory/shelfobject/action_modal.html

- Add the code for the required endpoint with the required serializers.  It performs server side filtering, sorting and paging.
- Add the modal and required things to display it.
- Add the table for displaying the information.
- Fix issue with the transfer out button that had a modal property not required anymore.
- Other fixes and improvements.
The table in the modal looks like this:

Transfer Available List implementation.

---

src/laboratory/api/serializers.py
src/laboratory/api/shelfobject.py
src/laboratory/static/js/shelfobjectedit.js
src/laboratory/static/laboratory/css/laboratory.css
src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/templates/laboratory/laboratoryroom_list.html
src/laboratory/templates/laboratory/shelfobject/action_modal.html

- Fix search and sorting in the shelfobject table/api.
- Improve UI a little bit.
- Other changes found during the development.

Improvements and UI.

---

src/auth_and_perms/management/commands/urlname_permissions.py
src/laboratory/api/shelfobject.py
src/laboratory/forms.py
src/laboratory/static/laboratory/js/base_modal_management.js
src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/static/laboratory/js/shelfobject_management.js
src/laboratory/static/laboratory/js/shelfobject_utils.js
src/laboratory/templates/laboratory/laboratoryroom_list.html
src/laboratory/templates/laboratory/shelfobject/action_modal.html
src/laboratory/templates/laboratory/shelfobject/shelfobject_observations.html
src/locale/es/LC_MESSAGES/django.po
src/presentation/templates/modal_template.html

Se conecto el status del shelfobject.
Se acato las observaciones

Connect update status

---

src/auth_and_perms/api/serializers.py
src/laboratory/shelfobject/forms.py
src/laboratory/shelfobject/serializers.py
src/report/forms.py
src/report/gtselects.py

Including changes about validate user access in a specific organization and laboratory through a serializer.
This changes were applied in furniture FurnitureLookup and ShelfLookup. Also required attr data-s2filter(laboratory and organization) were included in report/forms.py LaboratoryRoomReportForm class.

Move shelfobject to shelf

---

src/laboratory/shelfobject/forms.py

agregado los ids de laboratorio y organizacion en los widgets de objects ademas de eliminar atributos innecesarios

fixed form was use gtselect widgets

---

src/auth_and_perms/management/commands/urlname_permissions.py
src/laboratory/templates/laboratory/laboratoryroom_form.html

* Agrega permiso en el diccionario de permisos por url necesario para asignación por roles.
* Checa si el usuario tiene permisos para agregar y editar muebles.

Review laboratory view

---

fixtures/shelf_object_data.json
src/laboratory/tests/test_furniture.py
src/laboratory/tests/test_shelf.py
src/laboratory/tests/utils.py

* Prueba que verifica si un usuario con permisos requeridos y perteneciente a la organización puede obtener información disponible del estante.
* Prueba  caso no esperado pero posible de un usuario que no cuenta con los permisos necesarios y no pertenece a la organización.
* Archivo JSON con datos exclusivos para dichas pruebas con el fin de evitar conflictos con datos de otras pruebas que se vayan incorporando por otros.

Shelfobject tests

---

src/academic/views.py

Se excluyo los objectos que su cantidad sea menor o igual que 0

Ajuste a reservaciones

---

src/academic/static/js/procedure_list.js
src/academic/templates/academic/procedure_list.html
src/laboratory/static/js/procedures.js

Se realizaron las aplicaron todas las observaciones mencionadas en el issue https://github.com/Solvosoft/organilab/issues/262
Se corrigieron aspectos graficos de diversas vistas.
Se cambio el codigo de generate_reservation.
Se agregaron traducciones 
La creacion de la datatableAPI de MyProcedures

Correcciones a Issue 102

---

src/report/api/serializers.py

Se agrego atributo user previo de la extraccion del username en el serializer

Validar usuarios

---

src/report/templates/report/general_reports.html
src/report/views/furniture.py
src/report/views/lab_room.py
src/report/views/objects.py

Se corrigio la exportacion de reportes en formato XLS y se ajusto el tabledom

Correccion de exportacion de reporte xls

---

docs/source/api_procedure_template.rst
src/academic/api/serializers.py
src/academic/static/js/procedures.js
src/academic/templates/academic/detail.html
src/academic/templates/academic/procedure_list.html
src/auth_and_perms/management/commands/urlname_permissions.py
src/laboratory/templates/laboratory/logentry_list.html
src/laboratory/templates/laboratory/sustance/sustance_form.html
src/laboratory/views/furniture.py
src/laboratory/views/provider.py
src/laboratory/views/shelfs.py
src/locale/es/LC_MESSAGES/djangojs.po
src/presentation/templates/partials/derb_menu.html
src/report/utils.py

Se realizaron diversas mejoras:
- Se agregaron permisos faltantes en el modal de permission_management para asignarlos a roles nuevos en las vistas.
- Se agrego el campo created_by en la creacion de Furniture, Shelf y Providers.
- Se agrego el archivo procedures.js en la vista de listado de procedimientos que traía consigo la funcionalidad de eliminar.
- Se agregar uno permisos en los HTML de procedimientos para la eliminacion de observaciones en los pasos.
- Por ultimo se agrego un mensaje cuando el usuario no tiene el permiso cuando se intenta crear una reservacion de procedimiento; lo que sucede es que cuando un usuario que no tiene el permiso realiza la accion, este devuelve un status 302 en **AJAX* y no uno de la linea de 400, esto haciendo que no entre en el error de ajax si no en …

Test sistema kendrick

---

src/auth_and_perms/management/commands/urlname_permissions.py
src/presentation/templates/partials/sga_complements.html
src/sga/api/filterset.py
src/sga/api/recipients_viewset.py
src/sga/api/serializers.py
src/sga/static/sga/js/recipient_size.js
src/sga/templates/sga/recipient_size.html
src/sga/urls.py
src/sga/views/substance/forms.py
src/sga/views/substance/views.py

Inicio de modulo de creacion de tamaño de recipientes

Modulo de Tamaño de recipiente

---

src/laboratory/shelfobject/serializers.py

Se valido la creacion de shelfobjects con valores menores de 0

Validacion de shelfobject negativos

---

src/auth_and_perms/management/commands/urlname_permissions.py
src/locale/es/LC_MESSAGES/django.po
src/locale/es/LC_MESSAGES/djangojs.po
src/presentation/templates/partials/sga_complements.html
src/sga/api/recipients_viewset.py
src/sga/api/serializers.py
src/sga/static/sga/js/recipient_size.js
src/sga/templates/personal_template.html
src/sga/templates/sga/recipient_size.html
src/sga/templates/sga/substance/check_substances.html
src/sga/templates/sga/substance/list_substance.html

Validaciones, Traducciones y Permisos sobre el tamaño de recipiente

Recipient module

---

src/laboratory/models.py

Incluye unidad de medida como filtro en la cantidad usada de un estante.

Used capacity shelf

---

src/laboratory/models.py

Adiciona filtros de unidad de medida y exclusión de contenedores a la función de porcentaje de objetos en el modelo estante.

Filtros del estante por unidad de medidad en la función de porcentaje

---

src/laboratory/shelfobject/forms.py
src/laboratory/views/labroom.py

Definiendo formulario de contenedor que será utilizado en funciones como transferencias, movimientos y creación de sustancias.

Formulario de contenedor

---

src/laboratory/api/shelfobject.py
src/laboratory/shelfobject/serializers.py
src/laboratory/shelfobject/utils.py
src/laboratory/static/js/shelfobjectedit.js
tox.ini

Some changes in laboratory view
- Add parenthesis after function 'get_objects' to get all shelf objects by shelf when shelf does not have measurement unit.
- Remove raise from 'validate_measurement_unit_and_quantity' function.
- Add shelf object entry by 'save_object_action' function from move, increase and decrease actions.
- Reset delete container switchery from delete shelf object modal.

Revision pre merge

---

src/report/views/base.py

Fix error when try to access a report that not exists also validate if user dont belongs to the laboratory and organization

Check error 500

---

src/authentication/forms.py
src/laboratory/templates/laboratory/register_user_qr/login_register_user.html

Updating register user template.
Register user validate:
- Password field
- Confirm password field
- Email
- Phone

Fixing validate register user form

---

src/report/templates/report/base_pdf.html
src/risk_management/incidents.py
src/risk_management/templates/risk_management/incidentreport_detail.html
src/risk_management/templates/risk_management/incidentreport_pdf.html

**Updating incident report format, some details were:**
- Font size
- Font family
- Horizontal align
- Bold title and subtitles
- Space between subtitles
- Format report base template(logo, title, current date time, user, page number)
Move add button incident in incident detail view

Incident report

---

src/laboratory/templates/laboratory/furniture_form.html
src/laboratory/templates/laboratory/shelf_card.html
src/presentation/static/css/organilab.css

Fixed problem with the positions of the shelves in laboratory room because these not in the same positions than the furniture view

Shelves positions

---

Changelog
src/auth_and_perms/api/serializers.py
src/auth_and_perms/api/viewsets.py
src/auth_and_perms/forms.py
src/auth_and_perms/gtselects.py
src/auth_and_perms/management/commands/groups_by_views_without_org_lab.py
src/auth_and_perms/static/js/auth_and_perms/organization_manager.js
src/auth_and_perms/templates/auth_and_perms/list_organizations.html
src/auth_and_perms/urls.py
src/auth_and_perms/views/organizationstructure.py

Functionality: Organization admin user will assign permissions groups to profile users related to selected organization.
Some elements added were:
Form: Profile and groups fields.
GTSelect: Show users related to selected organization.
New tab "By profile" on right panel from "Manage Organizations" view.
Command: It creates basic permissions groups.
Issue:
#320

Profile group

---

src/auth_and_perms/views/__init__.py
src/risk_management/templates/risk_management/incidentreport_detail.html
src/risk_management/templates/risk_management/riskzone_detail.html
src/risk_management/templates/risk_management/riskzone_list.html

Fixed the access to media file for anonymous user to see any files except reports because this ones only authenticated users maybe can access

Fixing media file bug

---

.gitignore
docker/nginx_personalize.py
src/laboratory/api/shelfobject.py
src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/templates/laboratory/shelf_card.html

Fixing a problem about slip tag by comma, so it was fixed following the recommendations in Tagify official documentation.

Setting delimiter tag from laboratory view

---

src/laboratory/protocol/views.py
src/laboratory/tests/test_protocol.py

Adding permissions in protocols views

Protocols permissions

---

src/laboratory/tests/test_protocol.py

Adding permissions to the user that is using in the tests

fix protocol test

---

src/auth_and_perms/static/js/auth_and_perms/organization_manager.js

Message to user when a org is not selected.
Title modal relate user to org/lab was updated.

Changes from organization management

---

src/auth_and_perms/api/serializers.py
src/auth_and_perms/api/viewsets.py
src/auth_and_perms/forms.py
src/auth_and_perms/gtselects.py
src/auth_and_perms/node_tree.py
src/auth_and_perms/static/js/auth_and_perms/select_organization.js
src/auth_and_perms/templates/auth_and_perms/organization_buttons.html
src/auth_and_perms/templates/auth_and_perms/select_organization.html
src/auth_and_perms/tests/test_organizations.py
src/auth_and_perms/urls.py
src/auth_and_perms/views/organizationstructure.py
src/auth_and_perms/views/select_organization.py

Some changes were:
**GTSelect** 
- Organizations by user.(Organization Tree, sorted by level)
- Objects by organization.
**API(Table Results)**
- ShelfObjects by object and organization(search in all laboratories)
**API(GET method)**
- Get organization actions buttons when an organization is selected.
**Serializer**
- ValidateSearchShelfObjectSerializer(Validate search object is a valid parameter)

Search obj by organization view

---

src/auth_and_perms/static/js/auth_and_perms/organization_manager.js

Fixed bug in group selection not refreshing but adding when change the profile

Group Select

---

fixtures/groups/group.json
src/auth_and_perms/tests/base_manage_profile_groups.py
src/auth_and_perms/tests/gtapis/test_manage_profile_groups.py
src/auth_and_perms/tests/test_user_groups.py

Make some unittest for the profile group functionality in organization management view.
APIS that I do test:
1. For the API that using to update they groups. **UpdateGroupsByProfile**
2. GTSELECT for profiles(user) **UsersByOrganization.**
3. GTSELECT for groups. **GroupsByProfile**

Test profile group

---

fixtures/select_organization/objects_by_organization.json
src/auth_and_perms/api/serializers.py
src/auth_and_perms/gtselects.py
src/auth_and_perms/tests/select_organization/base.py
src/auth_and_perms/tests/select_organization/test_objects_by_organization.py
src/auth_and_perms/tests/select_organization/test_organization_buttons_by_user.py
src/auth_and_perms/tests/select_organization/test_organizations_by_user.py
src/auth_and_perms/tests/select_organization/test_shelfobjects_by_object_and_organization.py

**Tests List In Select Organization View**
**Get available objects by organization and user. → ObjectsByOrganizationViewTest(Base class)**
**Url name:** objbyorg-list
**Url:** /gtapis/objbyorg/
**Class:** auth_and_perms.gtselects.ObjectByOrganization
**Check level and position of relational tree organization(user access to organization list) → OrganizationsByUserViewTest(Base class)**
**Url name:** orgtree-list
**Url:** /gtapis/orgtree/
**Class:** auth_and_perms.gtselects.OrgTree
**Get all available shelf objects by organization(all laboratories) and object related(specific search)→ ShelfObjectsByObjectViewTest(Base class)**
**Url name:** auth_and_perms:api-searchshelfobjectorg-list
**Url:** /perms/api/searchshelfobjectorg/
**Class:** …

Select organization tests

---

src/auth_and_perms/gtselects.py

Fixing bug filter queryset

---

src/laboratory/shelfobject_container/serializers.py
src/laboratory/shelfobject_container/viewsets.py
src/laboratory/templates/laboratory/containers/container_list.html

- Fixing container by shelf filter.
- Adding substance column.

Filter containers by shelf table

---

fixtures/laboratory_data.json
src/api/utils.py
src/auth_and_perms/management/commands/urlname_permissions.py
src/laboratory/api/views.py
src/laboratory/static/js/formio.js
src/laboratory/templates/laboratory/complete_inform.html
src/laboratory/tests/test_inform.py
src/laboratory/urls.py

Add the new validation for DRF views, using the class _AllPermissionByAction_  class as a reference, it also fix  **CommentAPI** to validate is a user has the permissions to perform a specific action

New Validation to DRF views

---

src/laboratory/sustance/views.py
src/locale/es/LC_MESSAGES/django.po

Reactive edit button

---

docs/source/administrative_usage/informs.rst
docs/source/administrative_usage/procedure.rst
src/derb/static/formio/FormioController.js
src/derb/static/js/list.js
src/derb/templates/formBuilder/edit_view.html
src/derb/templates/formBuilder/form_list.html
src/laboratory/templates/laboratory/inform.html
src/locale/es/LC_MESSAGES/django.po
src/locale/es/LC_MESSAGES/djangojs.po
src/presentation/templates/partials/derb_menu.html

Following sections titles were modified :
My Informs
- Success text
- Error text
- Info text
- Warning text
- Subtitles
- Descriptions
Informs Templates
- Success text
- Error text
- Info text
- Warning text
- Subtitles
- Descriptions
Sidebar
- Dropdown menu
My Informs Table
- DOM and col space were modified.

Title informs templates

---

requirements.txt
src/laboratory/api/views.py
src/laboratory/templates/laboratory/equipment/list.html
src/locale/es/LC_MESSAGES/djangojs.po

Fixing bugs from:
- Creation equipment type
- Creation instrumental family
Removing dom from equipment table
Adding translations related to actions table CRUD.
Updating djgentelella version from project requirements file.

Fixing some bugs, removing dom and adding translations

---

src/laboratory/forms.py
src/locale/es/LC_MESSAGES/django.po

Username validation from create user by qr view.

Username validation

---

src/laboratory/static/laboratory/js/laboratory.js
src/laboratory/views/labroom.py

Also fixed the unnecessary table refresh when shelfobject radio change.
Fixed #364

Fixed shelfobject filtering allowing filter by code

---

src/laboratory/management/commands/precursor_report.py
src/laboratory/tasks.py

Fix error when the laboratory does not have a previous precursor report, also remove the report was is creating when use the command

Fix precursor task

---

Makefile
README.md

Readme file project was updated with some instructions to start the Organilab application. 
Related isuee: #375

Updating readme file instrucctions

---

src/laboratory/utils.py
src/laboratory/views/laboratory.py

Fixed error when access to this modulo don't show the list of qr that is belongs to the organization

Fix bug in registerqr

---

src/laboratory/api/filterset.py
src/laboratory/api/serializers.py
src/laboratory/api/views.py
src/laboratory/forms.py
src/laboratory/sustance/views.py
src/laboratory/templates/laboratory/sustance/list.html
src/laboratory/urls.py
src/laboratory/views/objects.py

Ya esta listo el CRUDAL utilizando Gentellela y django rest framework en el modulo de **Reactivos**

CRUDAL Gentellela Reactivos
